path: ../data2_grouped

train: train/images
val: valid/images
test: test/images

nc: 6
names: [ 'LiaoJinXiaXiYuan', 'MingQing', 'PreQin_BuCoin', 'PreQin_DaoCoin', 'QinHanWeiJinNanBei', 'SongDynasty' ]
